apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lxsm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-lxsm@sha256:1aa97797632cc9edb6d6bf4973c039b84916c4e0d6b6ad0e53c6b441c0732d18
        name: my-nodejs
        resources: {}
status: {}
